# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:O/ZgXBxnxIVOWJRcN++/gcr8rlHf7AM7fm5QeH7eBJg=,iv:EjQRFhPu8QE4JYMrraDX70pXD6FF6DaLRt9uwzI7MLw=,tag:5UpT+7sGgTEWOfCp0PdoaA==,type:str]
sops:
  age:
    - recipient: age1wlr3qlzjt7n5h8pz3434u9kvk8z3323rwwa0xp4ldp2sk6xt8s7qep4zss
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtS2Q2UXQwUE9PbDM3UU10
        Kzc0NmlPVWIwTWZqTnY3ZWlLY29oY1dkelNNCis4VnlJbGVnTlJpUEp1aG9nbSto
        Z3RkaitjdDV6L1FuN3FGQnRtM0dGTWMKLS0tIGhQSVdNaVZqRC96Q0VVUVoyQmZN
        MmNNUFJSbjRXK3FLbGZUOUFPd2g0U0EKtlvKfRF65RuNQPpai4haY9Pul/osaJX5
        MuvxeMjj0y6q8tmatkPuf0WEPXxHtV9SbtHRK9ZGM3yCYhCZgU/Lgw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-17T15:01:28Z"
  mac: ENC[AES256_GCM,data:G0Z922UlSG0JHzJZn6dl3hi83Bas4GaOoJ3Ku+l30u/Z7M35puD99kjcJnPxBKHZ0aXa9tM5sK2HIa1Jk5rYEXQwVfSEJx3oyRAxZEFWFp/YS/6HMc1AIvJkF8hgzLLL3lxxPHEBafeyilZuncyWPEEitJavORxxJmi8KgdgTSo=,iv:4RkEfy9uLtQFxJx85VgzhHfe4n77KGFsHNENjrDh4Jw=,tag:IyFiLd5vM8vp0i+jeQFWIw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
