# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:lDdYIF0pBZoa+dMh+OCDqT9KMSDIICx+xqlI3fnik1bCZnQm17/83qFpuYs/B5hnSKVrgaBfy3rQtMdIrIKKrDd5jIcFecNTQ8onyaBauWW7zGwKgd6Gw10sD/KtQYn5z63T2ZU5kLUL7VSMQQYOm+xKZ3Djdhly3HVNgi+7EdlraEJ9+IE5gW1KfFRPtb3G8OoATMD9Nivtp00ZNP8m9mSpNvsv3waDBE76wsu3IoFWkV5gf5qgdZyuu+sSljcGCdVuyCXs/MM=,iv:jeYf8oSJSK+lE6hFI+HKR0wfS4B3VtvbWSsRIvOCAKg=,tag:FCbcxu7eLDV/tpSJkjOuHQ==,type:str]
sops:
  age:
    - recipient: age1wlr3qlzjt7n5h8pz3434u9kvk8z3323rwwa0xp4ldp2sk6xt8s7qep4zss
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TE9WZDJPMnpUN0pVMHRj
        YXFwWWVBaWFPbXBPRWtvcVBNWDBFUS9vQ3djCjRmVEVxYjMzS3FtZUNJbmdIM0pw
        cm9lQXJoZkIwdmx4TUNCNFZrNThxT28KLS0tIEo4N0VGTHQ4ZVZjejhvbkxyMUtO
        YTJtU21sZmVxK3JkcXVqenFIWk9JR3cKMN5lKPy50ktIPfgkgvDV2NhtSqEUlW7e
        ZJtDE4FTJDazrE+0jhwWz+td8DrEVbtvvQIx2dh3M+Ru/pt/hFaGzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-17T15:01:28Z"
  mac: ENC[AES256_GCM,data:8yo+EXhR/fNfn1Ddhhy41Uk3/jocg7x9N9UleneTrrXK1lstue/12dhTSh97Il+/1H4S5t2m5XDssY+8PKWRZHkIpbQM5WsFGNLyEDTLQliQKWXwRbIE6DxEPF/UsneULHIbDo7saAg3Rbufm+3opSP1Ze3ct1CChUJqbbsYF+4=,iv:ZYtUEevwA1JTRcLT6nnfmw2/ncN92Pm4AGx6MYV/KWs=,tag:4fNTfaTXusKHUCMbssxhEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
